### ISSUE TITLE
pkg lint: Warn about long entries

### ISSUE THREAD

**Issue by hroncok** [devassistant/devassistant#280]
Dapi won't accept package_name longer than 200 chars (and similarly with other fields). Warn about it.

Copied from https://github.com/devassistant/daploader/issues/4

**Comment by tradej** [comment]
I have a patch ready - the only question is if we want to report this situation as a `WARNING` as proposed, or rather an `ERROR`. I lean towards the latter because:

**Comment by bkabrda** [comment]
+1 to ERROR.

**Comment by hroncok** [comment]
+1 to ERROR as well
