### ISSUE TITLE
GitHubCommandRunner._guess_reponame should not implicitly use $name

### ISSUE THREAD

**Issue by hroncok** [devassistant/devassistant#319]
`GitHubCommandRunner._guess_reponame` should not implicitly use `$name` as `reponame`, as `$name` might be anything, even something GitHub won't allow. Make the `reponame` argument mandatory and let assistant authors worry about what the repo should be called (most likely `$basename` or similar variables).

Relevant issue: https://github.com/devassistant/dap-python/issues/1

**Comment by bkabrda** [comment]
Other `_guess*` methods in `GithubCommandRunner` also experience this behaviour. I'll fix them as well.

**Comment by hroncok** [comment]
Other `_guess*` don't rely on variable that is usually set directly from the command line.

I think, to preserve almost current behavior, it is good idea to keep the guessing there, just not use `$name` but `$reponame` instead.

**Comment by bkabrda** [comment]
-1. No guessing should be no guessing, regardless of global variable name. Everything should be passed explicitly to the `github_*` command runner.

**Comment by hroncok** [comment]
ok

**Comment by hroncok** [comment]
I've also added login argument to all our assistants. If everything is fine, we need to bump their versions and release them on Dapi.
