### ISSUE TITLE
RFE: improve UX of a dap upload process

### ISSUE THREAD

**Issue by TomasTomecek** [devassistant/devassistant#324]
So I got to a point when I was about to upload my dap to dapi. To my surprise I really had to _upload_ something using a web form. What is the thing I should upload actually? Docs says "On DAPI, log in with Github or Fedora account and follow Upload a DAP link in the menu." So I followed. Went to "Upload a dap" page, there was a text with terms and conditions, input with form for uploading a file and that's it. Not a single word about what file should I provide (I assume it's a tarball created from my dap somehow).

Anyway, the main point of this is issue is that I certainly don't want to upload my daps via webform. I would love to have one of these two options:

1. Upload dap via CLI
2. Specify dap via git repo and {tag,branch} — when I push some commits to my git repo, I just tell dapi to sync with the repo and tell it to provide dap from branch "master" or tag "0.1".

**Comment by hroncok** [comment]
For the git thing, I guess we can use Travis to do the hard work for us. I'll investigate and create an example of .travis.yml that will do the lint checks and upload to dapi on tag.

**Comment by hroncok** [comment]
1. It is now possible to upload DAPs from command line with the dap DAP. Will document it soon.
2. I've prepared a Travis demo here: https://github.com/hroncok/dap-testtest/blob/master/.travis.yml

**Comment by hroncok** [comment]
Now both things are documented http://docs.devassistant.org/en/latest/developer_documentation/create_assistant/packaging_and_distributing.html

**Comment by TomasTomecek** [comment]
wow, looks awesome! great job!
