### ISSUE TITLE
Making command runners consistent in accepted arguments format

### ISSUE THREAD

**Issue by bkabrda** [devassistant/devassistant#327]
Some commands, for example `dda_*`, now accept arguments as lists. While this behaviour shouldn't be removed for 1.0, we should also make it possible to specify these as mappings (which contains argument names), as most of the new command runners do it. The new way should be the only documented way, the old way should be preserved for one or two releases and eventually removed (a warning should be printed for the assistants using the old way in 1.0).

**Comment by tradej** [comment]
Closed in https://github.com/devassistant/devassistant/commit/3f19fa99eb08219b0af5f70310cc469b26a1b21a and https://github.com/devassistant/devassistant/commit/d98095a01e024024551874b2b1551198d54acdcb. I am leaving the `DependenciesCommandRunner` as is (accepting a list of mappings) to keep the order of dependencies and consistency with the *Dependencies* section.
