### ISSUE TITLE
Grammar issues in configure.ac when generating a C project

### ISSUE THREAD

**Issue by robindegen** [devassistant/devassistant#332]
I'm using the latest Fedora 21 64-bit with DevAssistant 0.9.3

Steps to reproduce:
1. Generate a new C or C++ project
2. Open configure.ac

Issue 1:
"This line defines how what name will have output tarball"
This should be something like:
"This line defines the name of the output tarball" or "This line defines how the output tarball will be named.".

Issue 2:
"This line defines where are stored Makefiles for project and sources"
This should be something like:
"This line defines where Makefiles are stored for projects and sources."

**Comment by bkabrda** [comment]
Thanks for the report, we'll see that it gets fixed. Opened https://github.com/devassistant/dap-c/issues/1 for it.
