### ISSUE TITLE
Add support for a licensing folder in DAPs

### ISSUE THREAD

**Issue by tradej** [devassistant/devassistant#336]
Due to a change in Fedora Licensing Guidelines, it is necessary to differentiate licensing files from general documentation (see devassistant/dap2rpm#4). This requires a change in the DAP layout.

I suggest a folder called `licensing` be introduced in the root directory of the DAP, where the appropriate licensing files will be placed by the DAP developer. I think not having the `licensing` folder in a DAP should be allowed to keep backwards compatibility with DAPs that put licensing files in `doc`, but a warning would be in order when linted, I believe.

**Comment by hroncok** [comment]
I'm not sure if it is a good idea to bend a dap format just to fit in to RPM. I'm not necessarily against this step, if there is any other good reason. However, I cannot see it. This just adds more complexity to an already complex stuff needed to do when developing assistants.

Why shouldn't this be handled in specfile instead as in any other package?

**Comment by bkabrda** [comment]
+1 to what @hroncok says. I don't want to enforce this on DAP developers just because of RPM. This should be handled downstream by packagers.

**Comment by tradej** [comment]
I said that not having this field should be allowed precisely not to enforce anything on DAP developers. However, I think having this particular mechanics and recommending it in tutorials etc. would help packaging - not only RPM, but Deb and others too. In this case, the `-f` option in SPEC is pretty much a no-go, unless we left out the whole `doc` subdirectory and leave that to be specified manually.

If you don't want this feature, I'm fine with that, but I dare say automated packaging will be severely hindered.

**Comment by hroncok** [comment]
Using the `%file -f dap-files` construct disables adding more files? The file is generated by what part of the process? If the package maintainer specifies the license file somehow, cannot it be still automated?

I mean something like:

    %the_macro_that_also_generates_the_files_list -l doc/%{shortname}/LICENSE

**Comment by tradej** [comment]
Well, that could probably work... I'll have a look at it next week.

**Comment by hroncok** [comment]
I'm going to continue in discussion about this feature in devassistant/dap2rpm#4

**Comment by tradej** [comment]
I will implement the change based strictly within dap2rpm, based on @hroncok's suggestion in devassistant/dap2rpm#4, so I am closing this bug.
