### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by hroncok** [devassistant/devassistant#340]
On Python 2, when a Shell command (`cl` command runner) exits with bad exit code displaying a localized error message, DevAssistant tracebacks with UnicodeEncodeError.

Example:

    - cl: definitelynotacommand 

Invoke DevAssistant with `LANG=cs_CZ.UTF-8` to get the traceback, as `foo` returns `bash: definitelynotacommand: příkaz nenalezen` containing `ř` and `í`. Assuming `definitelynotacommand` is not in your path ;)

Here is a sample traceback:

```
DevAssistant traceback (most recent call last):
Error: No DevAssistant frames to print.

Traceback (most recent call last):
  File "/home/churchyard/Dokumenty/RedHat/devassistant/devassistant/venv/bin/da", line 9, in <module>
    load_entry_point('devassistant==0.10.1', 'console_scripts', 'da')()
  File "/home/churchyard/Dokumenty/RedHat/devassistant/devassistant/devassistant/cli/cli_runner.py", line 71, in run
    to_run.run(**parsed_args_decoded)
  File "/home/churchyard/Dokumenty/RedHat/devassistant/devassistant/devassistant/path_runner.py", line 56, in run
    error = self._log_if_not_logged(e)
  File "/home/churchyard/Dokumenty/RedHat/devassistant/devassistant/devassistant/path_runner.py", line 37, in _log_if_not_logged
    logger.error(str(err))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 26-27: ordinal not in range(128)

```

I guess `str(err)` is to blame.

**Comment by bkabrda** [comment]
So I tried to fix this in 77e2d1b. Can you please check if this doesn't break anything in general? (I'd appreciate any comments on the patch itself, too - @tradej please look at it as well)

**Comment by hroncok** [comment]
Fixed in the simple example:

```
run:
- cl: etrdyfugio
```

Still fails when trying to catch the error.

```
run:
- catch $was_exc, $exc:
  - cl: etrdyfugio
```

https://github.com/devassistant/devassistant/blob/master/devassistant/lang.py#L199

**Comment by hroncok** [comment]
After 733df79, both examples work.

**Comment by bkabrda** [comment]
Good catch, I don't know why I've missed that. Thanks.
