### ISSUE TITLE
Docs say: Copyright 2013, Bohuslav Kabrda, Petr Hracek.

### ISSUE THREAD

**Issue by hroncok** [devassistant/devassistant#351]
I believe there are more contributors to the docs, especially @tradej and me. I'd suggest something like:

Copyright 2013-2015, DevAssistant contributors

Maybe (if possible) with link to https://github.com/devassistant/devassistant/graphs/contributors

**Comment by bkabrda** [comment]
+1. These may also be in other places in the code, feel free to substitute them with the "DevAssistant contributors" attribution.

**Comment by tradej** [comment]
Let's do that, but I think we should also introduce a `CONTRIBUTORS` file, where these people would be mentioned (I vaguely recall it's necessary in some jurisdictions to have the names).

**Comment by hroncok** [comment]
Is it really necessarily a file? The information is available in git and here on GitHub.
