### ISSUE TITLE
Test suite fails on Mac

### ISSUE THREAD

**Issue by hroncok** [devassistant/devassistant#353]
Currently, our test suite fails on Mac OS X.

The output of py.test is here: https://gist.github.com/hroncok/7cba5df9c46f23b4c02b

This is a tracking bug for fixing this:

 * [x] TestCache.test_cache_reacts_to_new_changed_removed_assistants
 * [x] TestCache.test_cache_deletes_if_different_version
 * [x] TestYamlLoader.test_load_yaml_by_path_logs_and_returns_None_on_bad_syntax
 * [x] test_sha256sum (might just need to install the command)

**Comment by hroncok** [comment]
So, about the Cache tests, some of them are failing, because of this:

Linux:

    touch('a'); print(os.path.getctime('a')); time.sleep(0.1); touch('a'); print(os.path.getctime('a'))
    1427982471.24
    1427982471.34

**Comment by bkabrda** [comment]
Then we could use `time.sleep(1.0)` if on Mac, right?. Let's keep it `0.1` on Linux, since it works there and there's no need to slow down the test unnecessarily.

**Comment by hroncok** [comment]
I could "fix" some tests by using `time.sleep(1)` instead, but that would probably prelong the total time of the tests a lot.

Yes, I can setup a time variable for all the sleeps deepening on the platform.

**Comment by bkabrda** [comment]
Yeah, so let's decide on the sleep length based on platform; if someone figures out a smarter way sometime in the future, we can use that (we *could* probably use mocking, but it might hide subtle issues similar to this one, so let's not mock).
