### ISSUE TITLE
Allow listing all and available DAPs from DAPI

### ISSUE THREAD

**Issue by tradej** [devassistant/devassistant#356]
Currently, there is no way of listing all DAPs on DAPI, and available ones (i. e. those that are not installed). This should be easy to implement with `devassistant.dapi.dapicli.metadaps()` and `devassistant.dapi.dapicli.get_installed_daps()`.

I suggest that the command `da pkg list` be synonymous with `da pkg list --remote`, and show all DAPs on DAPI, so `da pkg list --installed` would show installed packages (current behaviour of `da pkg list`), and `da pkg list --available` would show the remote DAPs that are not installed.

**Comment by hroncok** [comment]
I suggest that `da pkg list` would keep it's behavior (i.e. list installed), but I agree we introduce `--remote` and `--available`.
