### ISSUE TITLE
pkg lint should run yaml_checker

### ISSUE THREAD

**Issue by hroncok** [devassistant/devassistant#367]
Currently, `pkg lint` only check is the DAP is packaged correctly, performing no tests about Assistants/Snippets contents what so ever. This could lead to a perfectly valid DAP containing invalid Assistants.

Considering we already have a way to check the Assistants for validity (yaml_checker), it should be relatively easy to run it on YAMLs contained in the DAP and report the errors to the user.

For some compatibility reasons, it should be possible to disable those checks with a command line switch.

**Comment by hroncok** [comment]
So I have the following now:

```
$ da pkg lint ../daps/dap-bad/python-0.11.dap 
...snip...
ERROR: python-0.11.dap: Source file assistants/crt/python.yaml:
  Problem in: (top level) -> fullnasme
Invalid section name: fullnasme
WARNING: python-0.11.dap: Empty YAML assistants/crt/python/flask.yaml
```

It is the first error message spread across multiple lines, but I guess it doesn't look so bad.

Do you like my decision that syntax error is error and empty file is warning?

**Comment by bkabrda** [comment]
The output LGTM and I think it's perfectly ok that syntax error is `ERROR`. Empty file is possible (although a bit weird), so `WARNING` is also ok in this case.
