### ISSUE TITLE
Split off YAML checker and DAP checker into separate package(s)

### ISSUE THREAD

**Issue by tradej** [devassistant/devassistant#371]
The use cases for DAP and YAML checking are becoming numerous (when uploading to DAPI, when linting with `da pkg lint`, when loading a DAP in `dap2rpm` from the top of my head). All other programs depending on devassistant as a whole is IMHO not the cleanest way to do it.

For version 1.0, I suggest that the YAML and DAP checking part be split off into a separate package (e. g. `devassistant-lint`), which can then be imported wherever necessary. If we go for this, I am fully aware that classes like `YamlLoader` etc. will be needed both by this hypothetical `devassistant-lint` package, and `devassistant-core` or whatever the main package will be called.

Ideas?

**Comment by hroncok** [comment]
The DAP checker originated in separate package https://github.com/devassistant/daploader and was merged to DevAssistant for the sake of keeping those things in one repo.

Splitting it again would IMO bring more pain - we would need to somehow sync the code in different repos, not only when releasing, but also when running CI.

**Comment by tradej** [comment]
Okay then, let's not do that.
