### ISSUE TITLE
DEVASSISTANT_PATH ignored when installing

### ISSUE THREAD

**Issue by tradej** [devassistant/devassistant#378]
When running
```bash
DEVASSISTANT_HOME=~/.devassistant DEVASSISTANT_PATH=/foo/bar/baz DEVASSISTANT_NO_DEFAULT_PATH=1 da pkg install qux
```
the package is installed in `DEVASSISTANT_HOME` still. The reason is that in https://github.com/devassistant/devassistant/blob/master/devassistant/dapi/dapicli.py#L40, only `DEVASSISTANT_HOME` is returned, no matter other variables. The function should account for `DEVASSISTANT_NO_DEFAULT_PATH` and `DEVASSISTANT_PATH` being set.

**Comment by hroncok** [comment]
I believe this is a correct behavior.

Daps are installed into DEVASSISTANT_HOME and loaded form DEVASSISTANT_HOME + DEVASSISTANT_PATH.

**Comment by hroncok** [comment]
See http://docs.devassistant.org/en/latest/user_documentation.html#where-are-the-assistants-located

**Comment by tradej** [comment]
This behaviour should be changed then, I believe, because it makes packaging DAPs in Fedora difficult. The reason is that if I set `DEVASSISTANT_HOME` to `%{buildroot}%{assistant_path}` during `%install`, DevAssistant uses that directory to store `.cache.yaml` and `lastrun.log`, which results in an RPM error with installed but unpackaged files.

Removing the files is, of course, possible, but is hardly a clean solution, and will have to be updated every time DevAssistant starts dropping a new file into `DEVASSISTANT_HOME`.

**Comment by hroncok** [comment]
I agree that this use case needs a better solution. Could you describe the behavior you expected?

**Comment by tradej** [comment]
I propose to make installing DAPs consistent with running assistants, i. e.:

* Setting `DEVASSISTANT_NO_DEFAULT_PATH` makes DevAssistant install packages into the first (writable?) entry on `DEVASSISTANT_PATH`
* All non-assistant files (cache, logs) will still be dropped into `DEVASSISTANT_HOME` (it is already required to be set)

I am not sure if the first bullet should necessarily contain the *writable* requirement, because since the user explicitly says not to use the default PATH, they are probably well aware about what's on the PATH they set.

**Comment by hroncok** [comment]
And if user wants the packages to actually be installed to `DEVASSISTANT_HOME`, they'll set it twice?

Like this?

    DEVASSISTANT_HOME=~/.foo DEVASSISTANT_PATH=~/.foo:/foo/bar/baz DEVASSISTANT_NO_DEFAULT_PATH=1 da pkg install qux

**Comment by tradej** [comment]
If the user wants to install to `DEVASSISTANT_HOME`, they don't set `DEVASSISTANT_NO_DEFAULT_PATH` in the first place, do they?

**Comment by hroncok** [comment]
I meant a different directory than the default one.

**Comment by tradej** [comment]
I may have understood the doc wrong, but wouldn't
```
DEVASSISTANT_HOME=~/.foo da pkg install qux
```
suffice then?

**Comment by hroncok** [comment]
It would now. Not with your proposal.

Or are you suggesting that without `DEVASSISTANT_NO_DEFAULT_PATH` packages are installed to `DEVASSISTANT_HOME` but when `DEVASSISTANT_NO_DEFAULT_PATH` is used, they are installed to first of `DEVASSISTANT_PATH`?

What if `DEVASSISTANT_NO_DEFAULT_PATH` and `DEVASSISTANT_HOME` is set, but not `DEVASSISTANT_PATH`?

**Comment by tradej** [comment]
> Or are you suggesting that without DEVASSISTANT_NO_DEFAULT_PATH packages are installed to DEVASSISTANT_HOME but when DEVASSISTANT_NO_DEFAULT_PATH is used, they are installed to first of DEVASSISTANT_PATH?

That's the idea. Consider this: When running assistants, you override all defaults if you specify `DEVASSISTANT_NO_DEFAULT_PATH` and provide explicit values to use in `DEVASSISTANT_PATH`. My proposition is analogical to that, because `DEVASSISTANT_HOME` is (in a vast majority of scenarios) by default a member of `DEVASSISTANT_PATH`. 

I am aware that technically speaking, my proposition doesn't 100% follow conventions because PATH is used as a location of binaries and scripts to run, but I believe the consistency outweighs the deviation from convention in this case.

> What if DEVASSISTANT_NO_DEFAULT_PATH and DEVASSISTANT_HOME is set, but not DEVASSISTANT_PATH?

I would expect DA to fail in this case both when installing and when running.

**Comment by bkabrda** [comment]
I'm ok with @tradej's proposal. I expect that we will use `DEVASSISTANT_NO_DEFAULT_PATH` only in tests/downstream rebuilds, so we should make the behaviour good for these usecases; also, I think the proposal makes sense regardless of the usecase, so feel free to do this.

**Comment by hroncok** [comment]
I'm in as well. I just wanted to be sure about the design.
