### ISSUE TITLE
Handful of GTK-related warnings when running da-gui

### ISSUE THREAD

**Issue by jnpkrn** [devassistant/devassistant#384]
```
$ da-gui
/usr/lib/python2.7/site-packages/devassistant/gui/main_window.py:49:
  Warning: The property GtkButton:yalign is deprecated and shouldn't
           be used anymore. It will be removed in a future version.
  self.builder.add_from_file(GLADE_FILE)
/usr/lib/python2.7/site-packages/devassistant/gui/main_window.py:49:
  Warning: The property GtkButton:xalign is deprecated and shouldn't
           be used anymore. It will be removed in a future version.
  self.builder.add_from_file(GLADE_FILE)
Gtk-Message: GtkDialog mapped without a transient parent.
             This is discouraged.
```

**Comment by hroncok** [comment]
Thanks for the report. What is the distribution an it's version? How was devassistant installed?

**Comment by jnpkrn** [comment]
Fedora 22, used `pip` because I am waiting for a response on stuck
`dnf update` command (rhbz#1244342).
```
# pip install devassistant
[...]
Successfully installed PyGithub-1.25.2 dapp-0.3.0 devassistant-0.11.1 ndg-httpsclient-0.4.0 progress-1.2
```

**Comment by hroncok** [comment]
Could you please also try with Python 3?

**Comment by jnpkrn** [comment]
Rerun with `pip3 install` and per warning messages, da-gui now resolves
to the Python 3 version (`/usr/lib/python3.4/site-packages/...`).
Otherwise, results are the same.

Note that the last line is emitted upon clicking "Install more..." button.

**Comment by tradej** [comment]
These warnings are a known issue as the original GUI was written for an older version of GTK. They shouldn't break anything, so I'm closing this as WONTFIX. If you experience actual usability issues, feel free to reopen.
