### ISSUE TITLE
'-' unexpectedly normalised to '_' in Django project name

### ISSUE THREAD

**Issue by ncoghlan** [devassistant/devassistant#388]
I created a Python Django project named "repo-integrator", which DA silently revised to "repo_integrator", not just at the Python module level, but also at the overall project level (including the name of the generated GitHub repo).

Perhaps the package name could be normalised separately from the overall project name?

**Comment by tradej** [comment]
Hi, thanks for filing the bug, please refer to the linked bug for discussion and solution.
