### ISSUE TITLE
Gnome 3.20 Window Resize problem. 

### ISSUE THREAD

**Issue by thunderbirdtr** [devassistant/devassistant#402]
Hello ; I installed from F24 repository and default looks just like this ; 

![screenshot from 2016-03-23 14-40-03](https://cloud.githubusercontent.com/assets/1688848/13985396/2899d6e8-f105-11e5-901f-6bc24f28a236.png)

Not the perfect view but when I enable "gtk-inspector" and change value of "resize"  and It's looks like this; 
(that's default)

![screenshot from 2016-03-23 14-42-16](https://cloud.githubusercontent.com/assets/1688848/13985458/8026d690-f105-11e5-910c-627e87576f43.png)

Value I changed from "gtk-inspector" is this ; 

![screenshot from 2016-03-23 14-42-00](https://cloud.githubusercontent.com/assets/1688848/13985475/99951f38-f105-11e5-8fad-93c52718da19.png)

I hope that would be help for the problem. 

Thank you.

**Comment by thunderbirdtr** [comment]
I made patch file for change I hope that will also help that out. 

--- /usr/lib/python3.5/site-packages/devassistant/gui/devel-assistant.glade
+++ /usr/lib/python3.5/site-packages/devassistant/gui/devel-assistant.glade.backup
@@ -8,7 +8,7 @@
     <property name="can_focus">False</property>
     <property name="border_width">6</property>
     <property name="title" translatable="yes">DevAssistant setup wizard</property>
-    <property name="resizable">false</property>
+    <property name="resizable">True</property>
     <property name="window_position">center</property>
     <property name="default_width">500</property>
     <property name="gravity">center</property>

**Comment by hroncok** [comment]
Thanks

**Comment by hroncok** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2016-3b4a9d34c4

**Comment by thunderbirdtr** [comment]
You're welcome. Thanks for fix
