### ISSUE TITLE
Can't identify git user configuration in included files

### ISSUE THREAD

**Issue by rudineirk** [devassistant/devassistant#403]
DevAssistant keeps asking for me to configure the git name and email, even if it's already configured. I have my name and email git configurations in an included gitconfig file, like this:

content of `~/.gitconfig`: 
```
[include]
  path = .gitconfig.user
# ... more configurations
```

and the content of `~/.gitconfig.user`: 
```
[user]
  name = My Full Name
  email = myemail@example.com
```

Tested on Fedora 23, with the Python -> Flask project

**Comment by hroncok** [comment]
This still returns your name? `git config --global user.name`

**Comment by rudineirk** [comment]
No, it doesn't return anything. It's weird, it works as intended when creating a commit.

Probably this isn't a DevAssistant bug.

**Comment by hroncok** [comment]
If I remember correctly, this is how we check it.

**Comment by rudineirk** [comment]
I moved my git user configurations to ~/.gitconfig for now, it's working as expected.

I sent this problem to the git mailing list [here](http://www.mail-archive.com/git@vger.kernel.org/msg90076.html), I think this issue may be closed
