### ISSUE TITLE
PHP - lamp project fails on create_database.php

### ISSUE THREAD

**Issue by mwd5650** [devassistant/devassistant#407]
When trying to create a PHP project in Dev assistant on Fedora 23. I get the following error when the create_database.php script runs:

Copying AMP source tree to /home/mdavis/public_html/Deer-app
pkexec /usr/libexec/da_auth &lt;&lt; DA_AS_USER_ROOT
bash /usr/share/devassistant/files/crt/php/lamp/apache_config.sh Deer-app /home/mdavis
DA_AS_USER_ROOT
Checking SELinux...
SELinux is: Permissive
Enabling httpd.service
Enabling and starting mysqld.service
Creating configuration file for Apache httpd
Checking whether UserDir is enabled
Restarting httpd.service
Restarting httpd.service done
php /usr/share/devassistant/files/crt/php/lamp/create_database.php
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mysqlnd.so' - /usr/lib64/php/modules/mysqlnd.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mysql.so' - /usr/lib64/php/modules/mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mysqli.so' - /usr/lib64/php/modules/mysqli.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/pdo_mysql.so' - /usr/lib64/php/modules/pdo_mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mysqlnd.so' - /usr/lib64/php/modules/mysqlnd.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mysql.so' - /usr/lib64/php/modules/mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mysqli.so' - /usr/lib64/php/modules/mysqli.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/pdo_mysql.so' - /usr/lib64/php/modules/pdo_mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0

dnf update has been run so I've got the latest version for Fedora 23. I checked that php-mysql package is installed although it tells me that it's skipping dependency php-mysqlnd with conflicts even though the package version is the exact same as what is already installed. see the output below

```
# dnf install php-mysql
Last metadata expiration check: 0:32:38 ago on Tue Jun 21 11:25:40 2016.
Package php-mysqlnd-5.6.22-1.fc23.i686 is already installed, skipping.
Dependencies resolved.
================================================================================
 Package             Arch           Version               Repository       Size
================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 php-mysqlnd         x86_64         5.6.22-1.fc23         updates         311 k

Transaction Summary
================================================================================
Skip  1 Package

Nothing to do.
Complete!
```

**Comment by hroncok** [comment]
I can smell an architecture mishmash. Try:

```
dnf install php-mysqlnd.x86_64 --best --allowerasing
```

**Comment by mwd5650** [comment]
ah! I see it now. you were right i686 package was installed instead of x86_64.

Thanks,
