### ISSUE TITLE
Old color palette was better

### ISSUE THREAD

**Issue by techtonik** [devassistant/devassistant#409]
http://doc.devassistant.org/en/v0.6.1/user_documentation.html
^ this looks much better than
http://doc.devassistant.org/en/v0.10.0/user_documentation.html
because it gives a sense that project is better maintained.
Layout and fonts are probably o.k., but colors were better before.

**Comment by hroncok** [comment]
Well I will not change the already public ones, and I'm not sure if any new will follow :(

**Comment by techtonik** [comment]
@hroncok is it impossible to use custom CSS on read the docs?

**Comment by hroncok** [comment]
I think it's possible.
